apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodedocker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nodedocker
  template:
    metadata:
      labels:
        app: nodedocker
    spec:
      containers:
      - image: registry.cloud.okteto.net/yudarmada/nodedocker:express-hello
        name: nodedocker

---

apiVersion: v1
kind: Service
metadata:
  name: nodedocker
  annotations:
    dev.okteto.com/auto-ingress: "true"
spec:
  type: LoadBalancer  
  ports:
  - name: "nodedocker"
    port: 80
  selector:
    app: nodedocker